import React, { Suspense } from "react";
import { Canvas } from "@react-three/fiber";
import {
  Loader,
  useGLTF,
  OrbitControls,
  PerspectiveCamera,
  Stars,
} from "@react-three/drei";
import styled from "styled-components";
import { Link } from "react-router-dom";

const Wrapper = styled.div`
  height: 100vh;
  width: 100vw;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  background: #171717;
`;

const Title = styled.h1`
  position: relative;
  top: 100px;
  left: 0px;
  font-weight: 900;
  font-size: 5em;
  margin: 0;
  color: peru;
  line-height: 0.6em;
  letter-spacing: -2px;
  text-align: left;
`;

const SubTitleBox = styled.div`
  width: 100vw;
  padding-top: 100px;
  display: flex;
  justify-content: space-around;
`;

const SubTitle = styled.h2`
  position: relative;
  top: 0px;
  left: 0px;
  padding: 10px;
  font-weight: 600;
  font-size: 3em;
  margin: 0;
  color: peru;
  /* line-height: 0.6em; */
  letter-spacing: -2px;
  text-align: left;
`;

const NextButton = styled.button`
  width: 50px;
  height: 50px;
  position: absolute;
  bottom: 10px;
  right: 10px;
  border-radius: 50%;
  background-color: #f5f5f5;
`;

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: overlaps (https://sketchfab.com/overlaps)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/91964c1ce1a34c3985b6257441efa500
title: Space exploration [WLP series #8]
*/
function Model({ url }) {
  const { nodes } = useGLTF(url);
  return (
    <group rotation={[-Math.PI / 2, 0, 0]} position={[0, -7, 0]} scale={7}>
      <group rotation={[Math.PI / 13.5, -Math.PI / 5.8, Math.PI / 5.6]}>
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.planet002.geometry}
          material={nodes.planet002.material}
        />
        <mesh
          geometry={nodes.planet003.geometry}
          material={nodes.planet003.material}
        />
      </group>
    </group>
  );
}

export default function About() {
  return (
    <Wrapper>
      <div className="bg" />
      <Title>
        What <span style={{ fontSize: "0.4em" }}>with </span>
        <span>MetaStep</span>
      </Title>
      <SubTitleBox>
        <div>
          <SubTitle>
            <div>Hello What the hell</div>
          </SubTitle>
        </div>
        <div>
          <SubTitle>
            <div>Hello What the hell</div>
          </SubTitle>
        </div>
      </SubTitleBox>
      <Canvas dpr={[1.5, 2]} linear shadows>
        <fog attach="fog" args={["#272730", 16, 30]} />
        <ambientLight intensity={0.75} />
        <PerspectiveCamera makeDefault position={[0, 0, 16]} fov={75}>
          <pointLight intensity={1} position={[-10, -25, -10]} />
          <spotLight
            castShadow
            intensity={2.25}
            angle={0.2}
            penumbra={1}
            position={[-25, 20, -15]}
            shadow-mapSize={[1024, 1024]}
            shadow-bias={-0.0001}
          />
        </PerspectiveCamera>
        <Suspense fallback={null}>
          <Model url="/scene.glb" />
        </Suspense>
        <OrbitControls
          autoRotate
          enablePan={false}
          enableZoom={false}
          maxPolarAngle={Math.PI / 2}
          minPolarAngle={Math.PI / 2}
        />
        <Stars radius={500} depth={50} count={1000} factor={10} />
      </Canvas>
      <div className="layer" />
      <Loader />
      <Link to="/characterani">
        <NextButton>NEXT</NextButton>
      </Link>
    </Wrapper>
  );
}
